[tool.ruff]
line-length = 200
target-version = "py310"
extend-select = ["E", "F", "I"]  # Errors, pyflakes, import sorting
fix = true
extend-exclude = [
    "*/migrations/*",   # Ignore Django migrations
    ".venv/*",           # Ignore virtualenv
    "__pycache__/*",    # Ignore cache
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
